---
- name: Ensure required Registry directories are created
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode | default('0755') }}"
  with_items:
    - { path: "{{ registry_config_dir }}", owner: root,     group: root }
    - { path: "{{ registry_data_dir }}",   owner: registry, group: registry }
    - { path: "{{ registry_logs_dir }}",   owner: registry, group: registry }

- name: Ensure Registry configuration is applied
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ registry_config_path }}"
    owner: root
    group: registry
    mode: '0640'
  notify: Restart Registry service
